[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/index.html"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ably"]

[dev]
  command = ""
  framework = ""
  targetPort = 8888
  port = 8889
  publish = "."

[build.environment]
  NODE_VERSION = "18"
